# Generated by Django 6.0.7 on 2026-07-25 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True, null=True, upload_to="profiles/"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tel",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "working_hours",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("business", "Business"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
