# Generated by Django 6.0.7 on 2026-07-25 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="offers/"
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfferDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("revisions", models.IntegerField()),
                ("delivery_time_in_days", models.PositiveIntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("features", models.JSONField(default=list)),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="offers_app.offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer detail",
                "verbose_name_plural": "Offer details",
                "ordering": ["price"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("offer", "offer_type"),
                        name="unique_offer_type_per_offer",
                    )
                ],
            },
        ),
    ]
