# Generated by Django 6.0.7 on 2026-07-25 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offerdetail",
            options={
                "ordering": ["id"],
                "verbose_name": "Offer detail",
                "verbose_name_plural": "Offer details",
            },
        ),
    ]
