# Generated by Django 6.0.7 on 2026-07-26 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers_app", "0002_alter_offerdetail_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
    ]
